Repository bbichul/bbichul-spring-backend, pull requests merged in 2021-12, with the labels that each got.

#56 Feature/mypage resolution/9
  build.gradle
  src/main/java/site/bbichul/controller/ResolutionController.java
  src/main/java/site/bbichul/controller/UserApiController.java
  src/main/java/site/bbichul/dto/SignupRequestDto.java
  src/main/java/site/bbichul/dto/UserInfoRequestDto.java
  src/main/java/site/bbichul/models/User.java
  src/main/java/site/bbichul/models/UserInfo.java
  src/main/java/site/bbichul/repository/UserInfoRepository.java
  src/main/java/site/bbichul/repository/UserRepository.java
  src/main/java/site/bbichul/security/WebSecurityConfig.java
  src/main/java/site/bbichul/service/ResolutionService.java
  src/main/java/site/bbichul/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/static/js/my_page.js
Labels: Status: Done

#57 #25 feat: 메인 페이지 명언 api 테이블 및 뼈대 잡기
  build.gradle
  src/main/java/site/bbichul/BbichulApplication.java
  src/main/java/site/bbichul/controller/WiseController.java
  src/main/java/site/bbichul/dto/WiseDto.java
  src/main/java/site/bbichul/models/Wise.java
  src/main/java/site/bbichul/repository/WiseRepository.java
  src/main/java/site/bbichul/security/WebSecurityConfig.java
  src/main/java/site/bbichul/service/TimeService.java
  src/main/java/site/bbichul/service/WiseService.java
  src/main/java/site/bbichul/utills/NaverCrawling.java
  src/main/resources/application.properties
  src/main/resources/static/js/main_page.js
  src/main/resources/static/main_page.html
Labels: Status: To Do, Type: Feature/Function

#58 #23 feat: 날씨 API 수정
  src/main/resources/static/js/main_page.js
Labels: Status: To Do, Type: Feature/Function

#59 Feature/setting goal/11
  build.gradle
  src/main/java/site/bbichul/controller/GoalController.java
  src/main/java/site/bbichul/controller/ResolutionController.java
  src/main/java/site/bbichul/dto/GoalRequestDto.java
  src/main/java/site/bbichul/dto/ResolutionRequestDto.java
  src/main/java/site/bbichul/models/UserInfo.java
  src/main/java/site/bbichul/repository/TimeRepository.java
  src/main/java/site/bbichul/service/GoalService.java
  src/main/java/site/bbichul/service/ResolutionService.java
  src/main/resources/static/js/my_page.js
Labels: Status: Done

#60 #29 #30 #31 팀 달력 추가하기 완성, 프론트 JS 코드 스프링에 맞게 수정
  src/main/java/site/bbichul/controller/CalendarController.java
  src/main/java/site/bbichul/dto/CalendarMemoDto.java
  src/main/java/site/bbichul/dto/CalenderDto.java
  src/main/java/site/bbichul/exception/BbichulErrorCode.java
  src/main/java/site/bbichul/models/CalendarMemo.java
  src/main/java/site/bbichul/models/TeamCalendar.java
  src/main/java/site/bbichul/models/User.java
  src/main/java/site/bbichul/models/UserCalendar.java
  src/main/java/site/bbichul/repository/CalendarMemoRepository.java
  src/main/java/site/bbichul/repository/CalendarRepository.java
  src/main/java/site/bbichul/repository/UserCalendarRepository.java
  src/main/java/site/bbichul/repository/UserRepository.java
  src/main/java/site/bbichul/service/CalendarService.java
  src/main/resources/static/js/calendar_page.js
Labels: Status: Done

#62 #61 fix : 캘린더 중복 코드 삭제
  src/main/resources/application.properties
  src/main/resources/static/js/calendar_page.js
Labels: Status: Done

#63 #34 feat: to do list
  src/main/java/site/bbichul/controller/TeamController.java
  src/main/java/site/bbichul/dto/TeamTaskRequestDto.java
  src/main/java/site/bbichul/models/TeamTask.java
  src/main/java/site/bbichul/repository/TeamTaskRepository.java
  src/main/java/site/bbichul/security/WebSecurityConfig.java
  src/main/java/site/bbichul/service/TeamService.java
  src/main/resources/static/js/team_page.js
  src/main/resources/static/team_page.html
Labels: Status: Done, Type: Feature/Function

#66 Feature/team page/33
  src/main/java/site/bbichul/controller/TeamController.java
  src/main/java/site/bbichul/repository/UserRepository.java
  src/main/java/site/bbichul/service/TeamService.java
  src/main/resources/application.properties
  src/main/resources/static/js/team_page.js
Labels: Status: Reviewing, Type: Feature/Function

#68 #67 fix: 팀 페이지 중복확인 버튼 관련 에러
  src/main/java/site/bbichul/controller/TeamController.java
  src/main/java/site/bbichul/models/Team.java
  src/main/java/site/bbichul/service/TeamService.java
  src/main/resources/static/js/team_page.js
  src/main/resources/static/team_page.html
Labels: Type: Bugfix/Function

#70 #69 feat: 회원가입 닉네임 중복체크, 유효성 검사 및 자잘한 에러 수정
  src/main/java/site/bbichul/controller/UserApiController.java
  src/main/java/site/bbichul/repository/UserRepository.java
  src/main/java/site/bbichul/security/WebSecurityConfig.java
  src/main/java/site/bbichul/service/UserService.java
  src/main/java/site/bbichul/utills/NaverScraping.java
  src/main/resources/application.properties
  src/main/resources/static/calendar_page.html
  src/main/resources/static/index.html
  src/main/resources/static/js/modal.js
  src/main/resources/static/js/team_page.js
  src/main/resources/static/main_page.html
  src/main/resources/static/my_page.html
  src/main/resources/static/team_page.html
Labels: Status: In Progress, Type: Feature/Document

#71 Feature/graph/6
  src/main/java/site/bbichul/controller/GraphController.java
  src/main/java/site/bbichul/dto/GraphRequestDto.java
  src/main/java/site/bbichul/models/Time.java
  src/main/java/site/bbichul/models/User.java
  src/main/java/site/bbichul/repository/TimeRepository.java
  src/main/java/site/bbichul/service/GraphService.java
  src/main/resources/static/js/my_page.js
Labels: Status: Done

#72 #35 feat:to to list 진행 상황 그래프 완료
  src/main/java/site/bbichul/controller/TeamController.java
  src/main/java/site/bbichul/dto/TeamProgressbarResponseDto.java
  src/main/java/site/bbichul/repository/TeamTaskRepository.java
  src/main/java/site/bbichul/service/TeamService.java
  src/main/resources/application.properties
  src/main/resources/static/js/team_page.js
Labels: Status: Done, Type: Feature/Function

#75 #10 feat: 회원탈퇴 기능
  src/main/java/site/bbichul/controller/UserApiController.java
  src/main/java/site/bbichul/dto/UserDto.java
  src/main/java/site/bbichul/models/User.java
  src/main/java/site/bbichul/repository/UserRepository.java
  src/main/java/site/bbichul/security/UserDetailsServiceImpl.java
  src/main/java/site/bbichul/service/GraphService.java
  src/main/java/site/bbichul/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/static/js/my_page.js
  src/main/resources/static/my_page.html
Labels: Status: In Progress, Type: Feature/Function

#74 Feature/get id/8
  src/main/java/site/bbichul/controller/ChangeUsernameController.java
  src/main/java/site/bbichul/dto/UsernameDto.java
  src/main/java/site/bbichul/models/User.java
  src/main/java/site/bbichul/repository/UserRepository.java
  src/main/java/site/bbichul/service/ChangeUsernameService.java
  src/main/resources/static/js/my_page.js
Labels: Status: Done

#76 #73 feat: 탈퇴한 유저 팀 정보 db에 반영
  src/main/java/site/bbichul/service/UserService.java
Labels: Type: Feature/Document

#78 #77 fix : 캘린더 버그 수정
  src/main/java/site/bbichul/service/CalendarService.java
  src/main/resources/static/js/calendar_page.js
  src/main/resources/static/js/modal.js
Labels: Status: Done

#89 #84 feat: 팀페이지 리팩토링(url 수정)
  src/main/java/site/bbichul/controller/TeamController.java
Labels: Status: Done, Type: Feature/Document

#93 Release1.1
  .platform/nginx/nginx.conf
  build.gradle
  src/main/java/site/bbichul/config/SwaggerConfig.java
  src/main/java/site/bbichul/controller/CalendarController.java
  src/main/java/site/bbichul/controller/ChangeUsernameController.java
  src/main/java/site/bbichul/controller/GoalController.java
  src/main/java/site/bbichul/controller/GraphController.java
  src/main/java/site/bbichul/controller/HomeController.java
  src/main/java/site/bbichul/controller/ResolutionController.java
  src/main/java/site/bbichul/controller/TeamController.java
  src/main/java/site/bbichul/controller/TimeController.java
  src/main/java/site/bbichul/controller/UserApiController.java
  src/main/java/site/bbichul/controller/WiseController.java
  src/main/java/site/bbichul/security/WebSecurityConfig.java
Labels: Status: Done, Type: Feature/Document

#96 Fix/calendar/95
  src/main/java/site/bbichul/controller/CalendarController.java
  src/main/resources/application.properties
Labels: Status: Done

#100 #99 feat: isStudying 테이블 studying 으로 변경
  src/main/java/site/bbichul/dto/TimeRequestDto.java
  src/main/java/site/bbichul/dto/UserDto.java
  src/main/java/site/bbichul/models/User.java
Labels: Status: In Progress, Type: Feature/Function

#101 feat: graph기준시간을 초에서 분으로 변경
  src/main/java/site/bbichul/service/GraphService.java
Labels: Status: Done

#106 #105 feat: 계정 복구 기능
  src/main/java/site/bbichul/controller/UserApiController.java
  src/main/java/site/bbichul/service/TimeService.java
  src/main/java/site/bbichul/service/UserService.java
Labels: Status: To Do, Type: Feature/Function

#108 Feature/recovery/105
  src/main/java/site/bbichul/models/User.java
  src/main/java/site/bbichul/security/UserDetailsServiceImpl.java
Labels: Status: To Do, Type: Feature/Document

#109 feat : 캘린더 이름 변경 기능 추가
  src/main/java/site/bbichul/controller/CalendarController.java
  src/main/java/site/bbichul/dto/CalendarDto.java
  src/main/java/site/bbichul/dto/CalenderDto.java
  src/main/java/site/bbichul/models/UserCalendar.java
  src/main/java/site/bbichul/repository/CalendarMemoRepository.java
  src/main/java/site/bbichul/service/CalendarService.java
  src/main/resources/application.properties
Labels: Status: Done

#111 #110 feat:to do list task 수정 기능 추가
  src/main/java/site/bbichul/controller/TeamController.java
  src/main/java/site/bbichul/models/TeamTask.java
  src/main/java/site/bbichul/service/TeamService.java
Labels: Status: In Progress, Type: Feature/Function

#113 #112 fix : 오탈자 수정
  src/main/java/site/bbichul/controller/CalendarController.java
  src/main/java/site/bbichul/security/WebConfig.java
Labels: Status: Done

#114 fix: teamService 수정
  src/main/java/site/bbichul/service/TeamService.java
Labels: Type: Bugfix/Function, Status: In Progress

#117 Feat/calendar test/116
  src/main/java/site/bbichul/exception/BbichulErrorCode.java
  src/main/java/site/bbichul/models/CalendarMemo.java
  src/main/java/site/bbichul/models/UserCalendar.java
  src/main/java/site/bbichul/service/CalendarService.java
  src/main/java/site/bbichul/utills/CalendarMemoValidator.java
  src/main/java/site/bbichul/utills/UserCalendarValidator.java
  src/test/java/site/bbichul/models/UserCalendarTest.java
  src/test/java/site/bbichul/service/CalendarServiceTest.java
Labels: Status: Done

#123 Feature/graph test/122
  .github/workflows/deploy.yml
  src/main/java/site/bbichul/controller/CalendarController.java
  src/main/java/site/bbichul/controller/ChangeUsernameController.java
  src/main/java/site/bbichul/controller/GraphController.java
  src/main/java/site/bbichul/controller/HomeController.java
  src/main/java/site/bbichul/controller/JwtAuthenticationFilter.java
  src/main/java/site/bbichul/controller/ResolutionController.java
  src/main/java/site/bbichul/controller/TeamController.java
  src/main/java/site/bbichul/controller/TimeController.java
  src/main/java/site/bbichul/controller/TotalTimeController.java
  src/main/java/site/bbichul/controller/UserApiController.java
  src/main/java/site/bbichul/controller/WiseController.java
  src/main/java/site/bbichul/dto/CalendarDto.java
  src/main/java/site/bbichul/dto/CalenderDto.java
  src/main/java/site/bbichul/dto/TimeRequestDto.java
  src/main/java/site/bbichul/dto/UserDto.java
  src/main/java/site/bbichul/exception/BbichulErrorCode.java
  src/main/java/site/bbichul/models/CalendarMemo.java
  src/main/java/site/bbichul/models/TeamTask.java
  src/main/java/site/bbichul/models/User.java
  src/main/java/site/bbichul/models/UserCalendar.java
  src/main/java/site/bbichul/repository/CalendarMemoRepository.java
  src/main/java/site/bbichul/repository/TimeRepository.java
  src/main/java/site/bbichul/repository/UserInfoRepository.java
  src/main/java/site/bbichul/security/UserDetailsImpl.java
  src/main/java/site/bbichul/security/UserDetailsServiceImpl.java
  src/main/java/site/bbichul/security/WebConfig.java
  src/main/java/site/bbichul/security/WebSecurityConfig.java
  src/main/java/site/bbichul/service/CalendarService.java
  src/main/java/site/bbichul/service/GoalService.java
  src/main/java/site/bbichul/service/GraphService.java
  src/main/java/site/bbichul/service/TeamService.java
  src/main/java/site/bbichul/service/TimeService.java
  src/main/java/site/bbichul/service/TotalTimeService.java
  src/main/java/site/bbichul/service/UserService.java
  src/main/java/site/bbichul/utills/CalendarMemoValidator.java
  src/main/java/site/bbichul/utills/UserCalendarValidator.java
  src/main/resources/application.properties
  src/test/java/site/bbichul/models/UserCalendarTest.java
  src/test/java/site/bbichul/service/CalendarServiceTest.java
  src/test/java/site/bbichul/service/GraphServiceTest.java
Labels: Status: Done

#126 Feature/fix graph test/122
  src/main/resources/application.properties
  src/test/java/site/bbichul/service/GraphServiceTest.java
Labels: Status: Done

#121 Feature/timetest/120 레파지토리 테스트
  build.gradle
  src/main/java/site/bbichul/BbichulApplication.java
  src/main/java/site/bbichul/controller/HomeController.java
  src/main/java/site/bbichul/controller/JwtAuthenticationFilter.java
  src/main/java/site/bbichul/dto/TimeRequestDto.java
  src/main/java/site/bbichul/models/Time.java
  src/main/java/site/bbichul/models/User.java
  src/main/java/site/bbichul/service/TimeService.java
  src/main/java/site/bbichul/utills/TimeValidator.java
  src/main/java/site/bbichul/utills/UserValidator.java
  src/main/resources/application-test.properties
  src/main/resources/application.properties
  src/test/java/site/bbichul/api/TimeControllerTest.java
  src/test/java/site/bbichul/api/UserControllerApiTest.java
  src/test/java/site/bbichul/models/TimeTest.java
  src/test/java/site/bbichul/models/UserTest.java
  src/test/java/site/bbichul/repository/UserRepositoryTest.java
  src/test/java/site/bbichul/service/TimeServiceTest.java
Labels: Status: To Do, Type: Feature/test

#128 #127 타임테스트 코드 작성후 깃허브액션 오류해결1
  src/main/java/site/bbichul/controller/HomeController.java
  src/test/java/site/bbichul/BbichulApplicationTests.java
Labels: Status: To Do, Type: Feature/test

#129 Feature/timesolution/127: 타임테스트 코드 깃액션 오류 해결
  src/main/java/site/bbichul/models/User.java
  src/test/java/site/bbichul/models/TimeTest.java
  src/test/java/site/bbichul/models/UserTest.java
  src/test/java/site/bbichul/repository/UserRepositoryTest.java
Labels: Type: Feature/test

#131 Feat/calendar test/130
  build.gradle
  src/main/java/site/bbichul/utills/CalendarMemoValidator.java
  src/test/java/site/bbichul/models/CalendarMemoTest.java
  src/test/java/site/bbichul/models/UserCalendarTest.java
  src/test/java/site/bbichul/service/CalendarServiceTest.java
Labels: Status: Done

#133 #124 feat: 목표설정 성공케이스 테스트
  src/test/java/site/bbichul/service/GoalServiceTest.java
Labels: Status: Done

#136 #135 feat: 회원탈퇴 후 7일 경과시 정보 자동삭제
  src/main/java/site/bbichul/models/CalendarMemo.java
  src/main/java/site/bbichul/models/Team.java
  src/main/java/site/bbichul/models/User.java
  src/main/java/site/bbichul/models/UserCalendar.java
  src/main/java/site/bbichul/repository/UserRepository.java
  src/main/java/site/bbichul/utills/NaverScraping.java
  src/main/java/site/bbichul/utills/UserDelete.java
Labels: Status: To Do, Type: Feature/Function

#137 Feature/add loggin system/134
  .gitignore
  build.gradle
  src/main/java/site/bbichul/controller/CalendarController.java
  src/main/java/site/bbichul/controller/GoalController.java
  src/main/java/site/bbichul/controller/GraphController.java
  src/main/java/site/bbichul/controller/HomeController.java
  src/main/java/site/bbichul/controller/ResolutionController.java
  src/main/java/site/bbichul/controller/TeamController.java
  src/main/java/site/bbichul/controller/TimeController.java
  src/main/java/site/bbichul/controller/TotalTimeController.java
  src/main/java/site/bbichul/controller/UserApiController.java
  src/main/java/site/bbichul/controller/WiseController.java
  src/main/java/site/bbichul/service/CalendarService.java
  src/main/java/site/bbichul/utills/UserCalendarValidator.java
  src/main/resources/application.properties
  src/main/resources/logback-spring.xml
Labels: Status: Done

#140 #139 feat: slack에 알림 연동해 상태관리하기
  build.gradle
  logback/apiLog(2021-12-22).log
  src/main/java/site/bbichul/controller/HomeController.java
  src/main/resources/application.properties
  src/main/resources/logback-spring.xml
Labels: Status: Reviewing, Type: Feature/Function

#142 fix:eb 변경
  .github/workflows/deploy.yml
  logback/apiLog(2021-12-22).log
  logback/apiLog(2021-12-23).log
  src/main/java/site/bbichul/controller/HomeController.java
Labels: Type: Bugfix/Function, Status: To Do

#143 fix: homecontroller 수정
  .github/workflows/deploy.yml
  src/main/java/site/bbichul/controller/HomeController.java
Labels: Type: Bugfix/Function, Status: In Progress

#146 #144 fix: yml 수정
  .github/workflows/docker.yml
Labels: Type: Bugfix/Function, Status: In Progress

#147 #144 fix: yml 중복 코드 삭제
  .github/workflows/docker.yml
  logback/apiLog(2021-12-23).log
Labels: Type: Bugfix/Function, Status: In Progress

#148 #144 fix: yml secrets 수정
  .github/workflows/docker.yml
Labels: Type: Bugfix/Function, Status: In Progress

#149 #144 fix:logback-spring.xml 수정
  logback/apiLog(2021-12-23).log
  src/main/resources/logback-spring.xml
Labels: Type: Bugfix/Function, Status: In Progress

#150 Fix/add validate user calendar/141
  src/main/java/site/bbichul/controller/CalendarController.java
  src/main/java/site/bbichul/repository/UserCalendarRepository.java
  src/main/java/site/bbichul/service/CalendarService.java
  src/main/java/site/bbichul/utills/CalendarMemoValidator.java
  src/main/java/site/bbichul/utills/CalendarServiceValidator.java
  src/main/java/site/bbichul/utills/CalendarValidatingOption.java
  src/main/java/site/bbichul/utills/UserCalendarValidator.java
  src/test/java/site/bbichul/service/CalendarServiceTest.java
Labels: Status: Done

#151 #144 fix: logback-spring.xml, webconfig 수정
  logback/apiLog(2021-12-23).log
  logback/apiLog(2021-12-24).log
  src/main/java/site/bbichul/security/WebSecurityConfig.java
  src/main/resources/application.properties
  src/main/resources/logback-spring.xml
Labels: Type: Bugfix/Function, Status: In Progress

#152 #144 fix: properties, logback-spring 수정
  logback/apiLog(2021-12-24).log
  src/main/resources/application.properties
  src/main/resources/logback-spring.xml
Labels: Type: Bugfix/Function, Status: In Progress

#153 #144 fix: slack 알람 주석처리
  logback/apiLog(2021-12-24).log
  src/main/resources/application.properties
  src/main/resources/logback-spring.xml
Labels: Type: Bugfix/Function, Status: In Progress

#154 #144 fix: 주석 처리한거 수정
  src/main/resources/application.properties
  src/main/resources/logback-spring.xml
Labels: Type: Bugfix/Function, Status: In Progress

#155 #144 fix: controller 수정
  logback/apiLog(2021-12-24).log
  src/main/java/site/bbichul/controller/HomeController.java
  src/main/java/site/bbichul/controller/SlackAlarmController.java
Labels: Type: Bugfix/Function, Status: In Progress

#158 Feat/test coverage/157
  build.gradle
Labels: Status: Done

#160 #159 fix : 유저캘린더 로직 에러 처리의 건
  logback/apiLog(2021-12-27).log
  src/main/java/site/bbichul/repository/UserCalendarRepository.java
  src/main/java/site/bbichul/service/CalendarService.java
  src/main/resources/application.properties
  src/test/java/site/bbichul/service/CalendarServiceTest.java
Labels: Status: Done

#161 fix : boot env
  src/main/resources/application.properties
Labels: Status: Done

#132 feat: teamService test코드
  src/main/java/site/bbichul/models/CalendarMemo.java
  src/main/java/site/bbichul/models/Team.java
  src/test/java/site/bbichul/models/TeamTaskTest.java
  src/test/java/site/bbichul/models/TeamTest.java
  src/test/java/site/bbichul/service/TeamServiceTest.java
Labels: Status: Done, Type: Feature/test

#163 #162 fix : 순환참조 에러 수정
  logback/apiLog(2021-12-22).log
  logback/apiLog(2021-12-23).log
  logback/apiLog(2021-12-26).log
  logback/apiLog(2021-12-27).log
  logback/apiLog(2021-12-28).log
  src/main/java/site/bbichul/models/Team.java
  src/main/java/site/bbichul/models/UserCalendar.java
Labels: Status: Done

#165 Feat/diffrence error solution/164
  logback/apiLog(2021-12-29).log
  src/main/java/site/bbichul/dto/CalendarMemoDto.java
  src/main/java/site/bbichul/dto/CalendarMemoResponseDto.java
  src/main/java/site/bbichul/models/CalendarMemo.java
  src/main/java/site/bbichul/models/UserCalendar.java
  src/main/java/site/bbichul/service/CalendarService.java
  src/main/resources/application.properties
Labels: Status: Done

#169 Feature/mypage team/167
  logback/apiLog(2021-12-30).log
  src/main/java/site/bbichul/controller/MyTeamController.java
  src/main/java/site/bbichul/service/MyTeamService.java
Labels: Status: Done

#170 #166 feat:팀페이지 리팩토링
  logback/apiLog(2021-12-30).log
  src/main/java/site/bbichul/controller/TeamController.java
  src/main/java/site/bbichul/dto/TeamTaskRequestDto.java
  src/main/java/site/bbichul/repository/TeamRepository.java
  src/main/java/site/bbichul/service/TeamService.java
  src/test/java/site/bbichul/service/TeamServiceTest.java
Labels: Status: Reviewing, Type: Feature/refactor

#172 #171 feat: 팀 페이지 테스트 코드 주석처리
  logback/apiLog(2021-12-30).log
  src/test/java/site/bbichul/service/TeamServiceTest.java
Labels: Status: In Progress, Type: Feature/test

#173 fix: 팀페이지 에러 수정
  logback/apiLog(2021-12-30) 2.log
  logback/apiLog(2021-12-30).log
  src/main/java/site/bbichul/models/Team.java
Labels: Type: Bugfix/Function, Status: Reviewing
