Repository bbichul/bbichul-spring-backend, pull requests merged in 2021-11, with the labels that each got.

#38 #36 feat: 카카오 소셜 로그인 및 시큐리티 추가
  build.gradle
  src/main/java/site/bbichul/BbichulApplication.java
  src/main/java/site/bbichul/controller/JwtAuthenticationEntryPoint.java
  src/main/java/site/bbichul/controller/JwtAuthenticationFilter.java
  src/main/java/site/bbichul/controller/UserApiController.java
  src/main/java/site/bbichul/controller/UserController.java
  src/main/java/site/bbichul/dto/JwtResponse.java
  src/main/java/site/bbichul/dto/SignupRequestDto.java
  src/main/java/site/bbichul/dto/SocialLoginDto.java
  src/main/java/site/bbichul/dto/UserDto.java
  src/main/java/site/bbichul/models/TimeStamped.java
  src/main/java/site/bbichul/models/User.java
  src/main/java/site/bbichul/models/UserRole.java
  src/main/java/site/bbichul/repository/UserRepository.java
  src/main/java/site/bbichul/security/UserDetailsImpl.java
  src/main/java/site/bbichul/security/UserDetailsServiceImpl.java
  src/main/java/site/bbichul/security/WebSecurityConfig.java
  src/main/java/site/bbichul/security/kakao/KakaoOAuth2.java
  src/main/java/site/bbichul/security/kakao/KakaoUserInfo.java
  src/main/java/site/bbichul/service/UserService.java
  src/main/java/site/bbichul/utills/JwtTokenUtil.java
  src/main/resources/application.properties
  src/main/resources/static/calender_page.html
  src/main/resources/static/index.html
  src/main/resources/static/js/calender_page.js
  src/main/resources/static/js/main_page.js
  src/main/resources/static/js/modal.js
  src/main/resources/static/js/my_page.js
  src/main/resources/static/js/team_page.js
  src/main/resources/static/main_page.html
  src/main/resources/static/my_page.html
  src/main/resources/static/team_page.html
Labels: Status: In Progress, Type: Feature/Function

#5 #4 docs: 띄워쓰기 수정2
  src/main/resources/static/index.html
Labels: Status: Done, Status: Reviewing

#42 #41 feat: 유저테이블 길이 수정 및 이메일 null true 수정
  src/main/java/site/bbichul/models/User.java
  src/main/resources/static/js/main_page.js
Labels: Type: Feature/Document, Type: Feature/refactor

#44 #24 feat: 타이머 기능을 위한 기초 구조 잡기
  .gitignore
  src/main/java/site/bbichul/BbichulApplication.java
  src/main/java/site/bbichul/controller/JwtAuthenticationFilter.java
  src/main/java/site/bbichul/controller/TimeController.java
  src/main/java/site/bbichul/dto/TimeRequestDto.java
  src/main/java/site/bbichul/models/Time.java
  src/main/java/site/bbichul/models/User.java
  src/main/java/site/bbichul/repository/TimeRepository.java
  src/main/java/site/bbichul/security/kakao/KakaoOAuth2.java
  src/main/java/site/bbichul/security/kakao/KakaoUserInfo.java
  src/main/java/site/bbichul/service/TimeService.java
  src/main/java/site/bbichul/service/UserService.java
  src/main/java/site/bbichul/utills/JwtTokenUtil.java
  src/main/resources/app.properties
  src/main/resources/application.properties
  src/main/resources/static/index.html
  src/main/resources/static/js/main_page.js
  src/main/resources/static/js/modal.js
Labels: Status: To Do, Type: Feature/Function

#46 #45 feat: 소셜로그인 -> 일반로그인으로 변경
  .gitignore
  build.gradle
  src/main/java/site/bbichul/controller/JwtAuthenticationEntryPoint.java
  src/main/java/site/bbichul/controller/JwtAuthenticationFilter.java
  src/main/java/site/bbichul/controller/TimeController.java
  src/main/java/site/bbichul/controller/UserApiController.java
  src/main/java/site/bbichul/controller/UserController.java
  src/main/java/site/bbichul/dto/SignupRequestDto.java
  src/main/java/site/bbichul/dto/SocialLoginDto.java
  src/main/java/site/bbichul/dto/UserDto.java
  src/main/java/site/bbichul/models/TimeStamped.java
  src/main/java/site/bbichul/models/User.java
  src/main/java/site/bbichul/models/UserRole.java
  src/main/java/site/bbichul/repository/TimeRepository.java
  src/main/java/site/bbichul/repository/UserRepository.java
  src/main/java/site/bbichul/security/kakao/KakaoOAuth2.java
  src/main/java/site/bbichul/security/kakao/KakaoUserInfo.java
  src/main/java/site/bbichul/service/TimeService.java
  src/main/java/site/bbichul/service/UserService.java
  src/main/java/site/bbichul/utills/JwtTokenUtil.java
  src/main/resources/static/calender_page.html
  src/main/resources/static/css/stylee.css
  src/main/resources/static/index.html
  src/main/resources/static/js/calender_page.js
  src/main/resources/static/js/main_page.js
  src/main/resources/static/js/modal.js
  src/main/resources/static/js/my_page.js
  src/main/resources/static/js/start_page.js
  src/main/resources/static/js/team_page.js
  src/main/resources/static/main_page.html
  src/main/resources/static/my_page.html
  src/main/resources/static/team_page.html
Labels: Status: In Progress, Type: Feature/Function

#49 #37 feat: 모델링 초안 및 연관관계(단방향)연결
  src/main/java/site/bbichul/controller/TimeController.java
  src/main/java/site/bbichul/dto/TimeRequestDto.java
  src/main/java/site/bbichul/dto/UserDto.java
  src/main/java/site/bbichul/models/CalendarMemo.java
  src/main/java/site/bbichul/models/Team.java
  src/main/java/site/bbichul/models/TeamCalendar.java
  src/main/java/site/bbichul/models/TeamTask.java
  src/main/java/site/bbichul/models/Time.java
  src/main/java/site/bbichul/models/User.java
  src/main/java/site/bbichul/models/UserCalendar.java
  src/main/java/site/bbichul/models/UserInfo.java
  src/main/java/site/bbichul/models/Wise.java
  src/main/java/site/bbichul/repository/UserRepository.java
  src/main/java/site/bbichul/service/TimeService.java
  src/main/java/site/bbichul/service/UserService.java
  src/main/resources/static/js/main_page.js
  src/main/resources/static/main_page.html
Labels: Status: To Do, Type: Feature/Document, Type: Feature/Function

#48 #47 feat: 공부시작 시 DB에 True(시작) 찍히는 기능
  src/main/java/site/bbichul/controller/TimeController.java
  src/main/java/site/bbichul/dto/TimeRequestDto.java
  src/main/java/site/bbichul/dto/UserDto.java
  src/main/java/site/bbichul/models/CalendarMemo.java
  src/main/java/site/bbichul/models/Team.java
  src/main/java/site/bbichul/models/TeamCalendar.java
  src/main/java/site/bbichul/models/TeamTask.java
  src/main/java/site/bbichul/models/Time.java
  src/main/java/site/bbichul/models/User.java
  src/main/java/site/bbichul/models/UserCalendar.java
  src/main/java/site/bbichul/models/UserInfo.java
  src/main/java/site/bbichul/models/Wise.java
  src/main/java/site/bbichul/repository/UserRepository.java
  src/main/java/site/bbichul/service/TimeService.java
  src/main/java/site/bbichul/service/UserService.java
  src/main/resources/static/js/main_page.js
  src/main/resources/static/main_page.html
Labels: Status: To Do, Type: Feature/Document

#50 #47 feat:공부시작 시 DB에 True(시작) ,끝날 씨 False 로 출퇴근 구분 기능
  src/main/java/site/bbichul/controller/TimeController.java
  src/main/java/site/bbichul/dto/TimeRequestDto.java
  src/main/java/site/bbichul/dto/UserDto.java
  src/main/java/site/bbichul/models/Time.java
  src/main/java/site/bbichul/security/UserDetailsServiceImpl.java
  src/main/java/site/bbichul/service/TimeService.java
  src/main/java/site/bbichul/service/UserService.java
Labels: Status: In Progress, Type: Feature/Function

#51 #27 #28 feat : 메모 저장하기, 불러오기 컨버팅
  .gitignore
  build.gradle
  settings.gradle
  src/main/java/site/bbichul/BbichulApplication.java
  src/main/java/site/bbichul/controller/CalendarController.java
  src/main/java/site/bbichul/controller/FrontController.java
  src/main/java/site/bbichul/dto/CalendarMemoDto.java
  src/main/java/site/bbichul/exception/BbichulErrorCode.java
  src/main/java/site/bbichul/exception/BbichulException.java
  src/main/java/site/bbichul/models/CalendarMemo.java
  src/main/java/site/bbichul/models/TeamCalendar.java
  src/main/java/site/bbichul/models/UserCalendar.java
  src/main/java/site/bbichul/repository/CalendarRepository.java
  src/main/java/site/bbichul/service/CalendarService.java
  src/main/resources/application.properties
  src/main/resources/static/calendar_page.html
  src/main/resources/static/css/calendar.css
  src/main/resources/static/js/calendar_page.js
  src/main/resources/static/main_page.html
  src/main/resources/static/my_page.html
  src/main/resources/static/team_page.html
Labels: Status: Done

#53 #52 feat: 사용자 팀 소속 여부 확인
  src/main/java/site/bbichul/controller/TeamController.java
  src/main/java/site/bbichul/dto/TeamRequestDto.java
  src/main/java/site/bbichul/repository/TeamRepository.java
  src/main/java/site/bbichul/repository/TeamTaskRepository.java
  src/main/java/site/bbichul/service/TeamService.java
  src/main/resources/application.properties
  src/main/resources/static/js/team_page.js
Labels: Status: Reviewing, Type: Feature/Function

#54 #32 feat: 팀 만들기
  .gitignore
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/site/bbichul/controller/TeamController.java
  src/main/java/site/bbichul/dto/TeamRequestDto.java
  src/main/java/site/bbichul/dto/UserDto.java
  src/main/java/site/bbichul/models/Team.java
  src/main/java/site/bbichul/models/User.java
  src/main/java/site/bbichul/repository/TeamRepository.java
  src/main/java/site/bbichul/service/TeamService.java
  src/main/resources/app.properties
  src/main/resources/application.properties
  src/main/resources/static/js/team_page.js
  src/main/resources/static/team_page.html
Labels: Type: Feature/Function

#55 #26 feat: 00시 기준 공부시간 (전날 + 종료한날) 저장 기능
  HELP.md
  src/main/java/site/bbichul/BbichulApplication.java
  src/main/java/site/bbichul/controller/TimeController.java
  src/main/java/site/bbichul/dto/TimeRequestDto.java
  src/main/java/site/bbichul/models/CalendarMemo.java
  src/main/java/site/bbichul/models/Team.java
  src/main/java/site/bbichul/models/TeamCalendar.java
  src/main/java/site/bbichul/models/TeamTask.java
  src/main/java/site/bbichul/models/UserCalendar.java
  src/main/java/site/bbichul/models/UserInfo.java
  src/main/java/site/bbichul/service/TimeService.java
  src/main/resources/application.properties
  src/main/resources/static/js/main_page.js
  src/main/resources/static/js/modal.js
  src/main/resources/static/main_page.html
Labels: Status: In Progress, Status: To Do, Type: Feature/Document
